services:
  todolist:  # Your ASP.NET Core app service
    image: neznajko/todolist:latest  # The Docker image to use
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    volumes:
      - ./db:/app/db  # Mount the local db folder to /app/db in the container
    restart: always  # Automatically restart the container if it stops